### ISSUE TITLE
Factory test

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/mch2022-firmware-ice40#1]
(ESP32 releases control over LCD)
- [ ] FPGA takes control over LCD and shows test pattern / image
- [ ] FPGA starts showing R, G, B cycle pattern on LED
- [ ] FPGA sets PMOD lines high, then low one by one
- [ ] FPGA tests PSRAM
(ESP32 writes test data over SPI)
- [ ] FPGA pulls interrupt line low (after psram self test completed or failed)
(ESP32 reads test data + PSRAM test result over SPI)
- [ ] After SPI read FPGA releases interrupt line
- [ ] FPGA echos data sent to the serial port (/dev/ttyACM1) with inverted case
(ESP32 tells RP2040 to test the FPGA serial port)

**Comment by smunaut** [comment]
Almost done, just needs testing by others.
Sequence is not exactly what's here but it tests all the same things.

FPGA code is in the `tnt/fpga-test` branch for now.  There is a branch for the ESP32 firmware with everything in it.
