### ISSUE TITLE
README Link to loader to is 404

### ISSUE THREAD

**Issue by a2800276** [badgeteam/mch2022-firmware-ice40#3]
This:

[Bitstream loader tool](https://github.com/badgeteam/mch2022-firmware-esp32/blob/master/tools/uart_fpga.py) and an bitstream for the FPGA ....

Link to uart_fpga.py does exist. Is the correct script: webusb_fpga.py in the https://github.com/badgeteam/mch2022-tools repo?

**Comment by smunaut** [comment]
That section is outdated ... yeah, now you need to use webusb_fpga.py ( and don't need to specify the ttyACM port obviously )

**Comment by Mecrisp** [comment]
Thank you for the hint, I updated the README file accordingly.

**Comment by a2800276** [comment]
I'll go through the README to help me with creating more FPGA docs on the badge.team site today and will probably submit some more stuff :)

The state of your documentation is really good, btw, kudos!

**Comment by Mecrisp** [comment]
Many thanks, I am glad you like it! If you need an additional piece of information or feel that anything is missing, please let me know.
